name: Deploy android to firebase
on:
  push:
    branches:
      - firebase
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      - name: Build android apk
        run: |
          cd android
          echo "AMSIGGEL_KEY_ALIAS=${{ secrets.AMSIGGEL_KEY_ALIAS }}" >> gradle.properties
          echo "AMSIGGEL_UPLOAD_STORE_FILE=${{ secrets.AMSIGGEL_UPLOAD_STORE_FILE }}" >> gradle.properties
          echo "AMSIGGEL_UPLOAD_STORE_PASSWORD=${{ secrets.AMSIGGEL_UPLOAD_STORE_PASSWORD }}" >> gradle.properties
          echo "AMSIGGEL_UPLOAD_KEY_PASSWORD=${{ secrets.AMSIGGEL_UPLOAD_KEY_PASSWORD }}" >> gradle.properties
          ./gradlew assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_ANDROID_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: android/app/build/outputs/apk/release/app-release.apk
          groups: internal